# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  knightschallenge:
    image: knightschallenge
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5259:5259
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"